### ISSUE TITLE
[Mod] The seasons management override seems to bug with the body temperature

### ISSUE THREAD

**Issue by SylvainMarty** [JulienLaclaverie/PZ_DieTonightMap#13]
I have this stacktrace all 10 minutes ingame :

```
1494756690381 -------------------------------------------------------------
1494756690381 attempted index: getBodyTemperature of non-table: null
1494756690381
1494756690382 -----------------------------------------
1494756690382 STACK TRACE
1494756690382 -----------------------------------------
1494756690383 function: updateBodyTemperature -- file: season.lua line # 129
1494756690383 function: EveryTenMinutes -- file: season.lua line # 45
java.lang.RuntimeException: attempted index: getBodyTemperature of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1549)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:473)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1727)
        at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1672)
        at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:53)
        at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:81)
        at zombie.Lua.Event.trigger(Event.java:37)
        at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:61)
        at zombie.GameTime.update(GameTime.java:903)
        at zombie.gameStates.IngameState.UpdateStuff(IngameState.java:420)
        at zombie.gameStates.IngameState.update(IngameState.java:1274)
        at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
        at zombie.GameWindow.logic(GameWindow.java:660)
        at zombie.GameWindow.run(GameWindow.java:1273)
        at zombie.GameWindow.maina(GameWindow.java:1049)
        at zombie.gameStates.MainScreenState.main(MainScreenState.java:180)
1494756690391
1494756690392 -----------------------------------------
1494756690392 STACK TRACE
1494756690392 -----------------------------------------
1494756690393 function: updateBodyTemperature -- file: season.lua line # 129
1494756690393 function: EveryTenMinutes -- file: season.lua line # 45
```

**Comment by SylvainMarty** [comment]
Apparemment, le code de season.lua aurait été fait sous la branche Vehicule Build Tech...
Proof : `local vehicleTemp = VehicleUtils.getBodyTemperature(player)` (il s'agit de cette ligne qui plante)

A voir si du coup, on prévoit l'intégration de la future update mais il faut la rendre compatible avec la version stable actuelle...

**Comment by JulienLaclaverie** [comment]
Ah ouais carément ouais

**Comment by JulienLaclaverie** [comment]
Should be fixed with my last commit
