### ISSUE TITLE
Right click on campire cause issues though they works perfectly

### ISSUE THREAD

**Issue by JulienLaclaverie** [JulienLaclaverie/PZ_DieTonightMap#20]
`java.lang.RuntimeException: missing argument #1to 'sub'
	at se.krka.kahlua.vm.KahluaUtil.getArg(KahluaUtil.java:389)
	at se.krka.kahlua.vm.KahluaUtil.getStringArg(KahluaUtil.java:339)
	at se.krka.kahlua.stdlib.StringLib.getStringArg(StringLib.java:680)
	at se.krka.kahlua.stdlib.StringLib.sub(StringLib.java:773)
	at se.krka.kahlua.stdlib.StringLib.call(StringLib.java:118)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:983)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1727)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1672)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:53)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:81)
	at zombie.Lua.Event.trigger(Event.java:37)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:181)
	at zombie.Lua.LuaEventManager.triggerEventGarbage(LuaEventManager.java:193)
	at zombie.Lua.LuaManager$GlobalObject.triggerEvent(LuaManager.java:2235)
	at sun.reflect.GeneratedMethodAccessor381.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:61)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:199)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:72)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:983)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1727)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1672)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:53)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:81)
	at zombie.Lua.Event.trigger(Event.java:37)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:148)
	at zombie.ui.UIManager.update(UIManager.java:1232)
	at zombie.GameWindow.logic(GameWindow.java:613)
	at zombie.GameWindow.run(GameWindow.java:1273)
	at zombie.GameWindow.maina(GameWindow.java:1049)
	at zombie.gameStates.MainScreenState.main(MainScreenState.java:180)
1495135269599 
1495135269599 -----------------------------------------
1495135269599 STACK TRACE
1495135269600 -----------------------------------------
1495135269600 Callframe at: sub
1495135269600 function: stringStarts -- file: luautils.lua line # 9
1495135269600 function: doInteractMenu -- file: ISGateInteractionMenu.lua line # 39
1495135269600 Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@1bc1d7f7
1495135269601 function: createMenu -- file: ISWorldObjectContextMenu.lua line # 1204
1495135269601 function: createMenu -- file: ISMenuContextWorld.lua line # 46
1495135269603 function: createWorldMenu -- file: ISContextManager.lua line # 28
1495135269603 function: doRClick -- file: ISObjectClickHandler.lua line # 45
1495135269603 function: onObjectRightMouseButtonUp -- file: ISObjectClickHandler.lua line # 231`

**Comment by JulienLaclaverie** [comment]
The error seems to come form the line `if v and luautils.stringStarts(v:getSprite():getName(), "security_01_") then` which is line 39 of `ISWorldObjectContextMenu.lua`
